name: NodeJS Build & Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the test environment'
        required: true
        default: 'master'
        type: choice
        options:
          - master
          - development
      test_suite:
        description: 'Choose the test suite'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - regression
      test_vcpNameSpace:
         description: 'Provide the VCP name space'
         required: true
         default: 'master'
      test_sairClient:
         description: 'Provide the sair client'
         required: true
         default: 'wpuk-master'
      test_MarchantStatusIndex:
         description: 'Provide marchant status index'
         required: true
         default: 'smoke'
jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/included
    steps:
      - name: Set vcp Name Space
        run: echo "vcpadminnaespace=${{ github.event.inputs.test_vcpNameSpace }}" >> $GITHUB_ENV
      - name: Set sair Client
        run: echo "sairclient=${{ github.event.inputs.test_sairClient }}" >> $GITHUB_ENV
      - name: Set Marchant Status Index
        run: echo "MERCHANTSTATUS_INDEX=${{ github.event.inputs.test_MarchantStatusIndex }}" >> $GITHUB_ENV
      - name: Use the environment variable
        run: |
          echo "Deploying to: $sairclient"
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.environment }}" == "master" ]; then
            if [ "${{ github.event.inputs.test_suite }}" == "smoke" ]; then
              npm run test:mst-smoke | tee cypress-output.txt
            else
              npm run test:mst-regression
            fi
          else
            if [ "${{ github.event.inputs.test_suite }}" == "smoke" ]; then
              npm run test:dev-smoke
            else
              npm run test:dev-regression
            fi
          fi
      
      - name: Check test results
        if: github.event.inputs.test_suite == 'smoke'
        run: |
          if grep -q "All specs passed" cypress-output.txt; then exit 0; else exit 1; fi
      
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            cypress/screenshots/**
            cypress/videos/**
